# Generated by Django 3.2.7 on 2021-09-14 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_Photo_App', '0003_quotes_quotes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog_Photo_App.quotes_category'),
        ),
    ]
